#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.5'

networks:
  secretmgmt:
    name: secrethub
    driver: bridge

volumes:
  graviteebot-data:

services:

  secrethub_operator:
    image: quay.io/gravitee-lab/secrethub_operator:${SHUB_OPERTATOR_VERSION}
    build:
      context: oci/operator
      args:
        # + ...
        - SECRETHUB_NAMESPACE=graviteeio-io
        - SECRETHUB_REPO=apim-stack
    container_name: secrethub_operator
    restart: 'no'
    command: [ "/gravitee-bot/run.sh" ]
    stdin_open: true
    tty: true
    # ports:
      # - "8444:8083"
    volumes:
      - ./.gravitee-bot/.secrets:/gravitee-bot/.secrets
      # # [graviteebot-data] named volume will be used to
      # # share secrethub data to another container in
      # # this [docker-compose.yml], for another task execution
      # - graviteebot-data:/gravitee-bot/.data
    environment:
      - SECRETHUB_NAMESPACE=gravitee-lab
      - SECRETHUB_REPO=apim-gateway
    networks:
      - secretmgmt
